project:
  type: website
  output-dir: docs

website:
  title: "Nomad's Wonderland"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/digital-nomad-cheng

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



